appenders:
  console:
    kind: console
    encoder:
      pattern: "{date(%Y-%m-%d %H:%M:%S)}  {highlight({level}):5}    {module}:{line}   {message}  {n}"

  file:
    kind: file
    path: "log/eugene_vm.log"
    # 保留历史日志
    append: true
    encoder:
      pattern: "{date(%Y-%m-%d %H:%M:%S)}  {highlight({level}):5}    {module}:{line}   {message}  {n}"

# 全局配置
root:
  level: debug
  appenders:
    - console
    - file
